#forward-backward parameters
etas: 1.0
cfg_scale_src: 3.5
cfg_scale_tar: 15
#feature extraction
steps: 100
save_steps: 100
extract_reverse: False
# general
seed: 1
device: 'cuda'
output_path: 'PNP-results/nuscenes_mini'

# data
image_path: 'data/nuscenes_mini.jpg'

# diffusion
sd_version: '1.5'
guidance_scale: 7.5
n_timesteps: 100
prompt: snowy day,The image shows a city street scene. 
  There are several parked cars on the side of the road, and a few cars are in motion. 
  The street is lined with buildings that appear to be of a similar architectural style, suggesting an urban area with a mix of residential and possibly commercial buildings.
  There are no visible people in the image, and the overall atmosphere is calm and quiet. The street is marked with yellow lines, indicating a two-way traffic pattern.
negative_prompt: sunny,blurry, black, low res, unrealistic

# pnp injection thresholds, ∈ [0, 1]
pnp_attn_t: 0.5
pnp_f_t: 0.8
