#feature extraction
steps: 200
save_steps: 200
extract_reverse: False
# general
seed: 1
device: 'cuda'
output_path: 'PNP-results/00002'

# data
image_path: 'data/00002.jpeg'

# diffusion
sd_version: '1.5'
guidance_scale: 7.5
n_timesteps: 50
prompt: snowy-day,car,truck,building,sky,tree,road,sidewalk,person,bridge,railing,signboard,traffic,plant,fence,
  The image depicts a busy city street with multiple cars driving down the road. The
  overall atmosphere of the image is that of a bustling urban environment with a mix
  of vehicles and pedestrians.
negative_prompt: sunny,blurry, black, low res, unrealistic

# pnp injection thresholds, ∈ [0, 1]
pnp_attn_t: 0.5
pnp_f_t: 0.8
